title: Manas Bhargava
logo: /assets/img/manas-profile.jpeg
email: mbhargav@ist[dot]ac[dot]at
description: PhD student in the digital fabrication group at IST Austria.
favicon: true
color-scheme: auto
domain: https://manas-avi.github.io/       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://https://manas-avi.github.io/  # the base hostname and protocol for your site, e.g. http://example.com


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/manas-avi
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/manas-bhargava-b36463121/
  - name: Twitter
    icon: <i class="fa-brands fa-twitter"></i>
    link: https://twitter.com/Manas161997/  
  # - name: ISTA
  #   icon: 
  #   link: hhttps://ist.ac.at/en/research/bickel-group/    

navigation:
  # - name: Readme
    # link: ./index.html
    # sublist:
    #   - name: Image
    #     link: ./index.html#small-image
  # - name: Another Page
  #   link: ./another-page.html
